"""initial_schema

Revision ID: bc008fb8fdc3
Revises: 
Create Date: 2026-05-23 22:26:30.145136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc008fb8fdc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=False),
    sa.Column('inbound_email', sa.String(), nullable=False),
    sa.Column('meta_token_enc', sa.String(), nullable=False),
    sa.Column('meta_phone_id_enc', sa.String(), nullable=False),
    sa.Column('propspace_key_enc', sa.String(), nullable=False),
    sa.Column('listing_price_min', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('listing_price_max', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('timezone', sa.String(), server_default=sa.text("'Asia/Dubai'"), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('plan', sa.String(), server_default=sa.text("'starter'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('inbound_email')
    )
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_emails',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('html_body', sa.String(), nullable=True),
    sa.Column('text_body', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('raw_email_id', sa.UUID(), nullable=True),
    sa.Column('prospect_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('property_ref', sa.String(), nullable=True),
    sa.Column('portal_source', sa.String(), nullable=True),
    sa.Column('budget_min_aed', sa.Integer(), nullable=True),
    sa.Column('budget_max_aed', sa.Integer(), nullable=True),
    sa.Column('timeline_days', sa.Integer(), nullable=True),
    sa.Column('financing', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('score_reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'RAW'"), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('propspace_lead_id', sa.String(), nullable=True),
    sa.Column('injected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_email_id'], ['raw_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_broker_id'), 'leads', ['broker_id'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('wa_message_id', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_lead_id'), 'conversation_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_wa_message_id'), 'conversation_messages', ['wa_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_wa_message_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_lead_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_broker_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('raw_emails')
    op.drop_table('webhook_logs')
    op.drop_table('brokers')
    # ### end Alembic commands ###
